### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by dimqua** [bogachenko/freefox#39]
Почему для Fennec используется `user.js`, а не `mozilla.cfg`? И имеет ли вообще смысл поддерживать самостоятельные версии этих файлов для Firefox и Fennec?

**Comment by dimqua** [comment]
И ещё, предложение. Возможно, не стоит поддерживать `Update.bat` и `prefsCleaner.bat`, т.к. на Windows тоже есть BASH и shell-версии этих скриптов тоже должны работать.

**Comment by bogachenko** [comment]
> Почему для Fennec используется `user.js`, а не `mozilla.cfg`?

Разве `mozilla.cfg` поддерживается для андройда? Я гуглил (например вот https://support.mozilla.org/ru/questions/1202266) говорили, что нет. Собственно я даже не знаю куда пихать этот самый файл в ведройде, поэтому я ограничился `user.js`. Если это измениться или если я владею не правильной инфой, то посвяти меня.

> И имеет ли вообще смысл поддерживать самостоятельные версии этих файлов для Firefox и Fennec?

Поддерживаю разные версии, т.к часть настроек из Firefox нет в Fennec и наоборот. Что то типа Save2Size.

**Comment by dimqua** [comment]
>Собственно я даже не знаю куда пихать этот самый файл

Да я и сам не пробовал, вот и поинтересоваться решил. :-)

**Comment by bogachenko** [comment]
@dimqua 

> 
> 
> И ещё, предложение. Возможно, не стоит поддерживать `Update.bat` и `prefsCleaner.bat`, т.к. на Windows тоже есть BASH (и многое другое) и shell-версии этих скриптов тоже должны работать.


Update.bat, как и  Update.sh скорее всего удалю его, однако скажу вот, что - Это скрипт использует wget, это консольная команда, (да я знаю, что существует версия и под винду) которая пользуется преимущественно на линкусе. wget, (curl?) подтягиваются в линуксе в качестве зависимости к какому-нидудь N установленному пакету. Он там всегда будет, это неотъемлемо. А для ~проклятой~ венды программа wget не подтянется, фаворит на венде это ГУЙ, а не консольные программы. И вряд ли кто либо вообще ей пользуется там? Поэтому возникает вопрос, а как тогда вообще с консольки скачать файл на винде? Ответ:
```bat
powershell -Command "(New-Object Net.WebClient).DownloadFile('ссылкаНаЧтоЛибо', 'ПутьСохранения')"
```
наверняка есть еще какой-нибуть убитый способ это сделать, но я его не знаю

***

prefsCleaner.bat это файл я спиздил с ghack (и чучуть модифицировал), как ты  мог догадаться. Так вот там разный способ проверки запуска программы. В винде он чекает обычным ~человеческим способом~:

```bat
:ProcessСheck
TASKLIST /FI "IMAGENAME eq firefox.exe" 2>NUL | FIND /I /N "firefox.exe">NUL
TASKLIST /FI "IMAGENAME eq thunderbird.exe" 2>NUL | FIND /I /N "thunderbird.exe">NUL
IF NOT ERRORLEVEL 1 (
	CLS
	CALL :message "This profile is used. Close your browser or email program and try again."
	ECHO:
	PAUSE
	CLS
	CALL :message "Resuming..."
	TIMEOUT 5 /nobreak >nul
)
GOTO :EOF
```

в линуксе:

```sh
ProcessСheck() {
	while [ -e webappsstore.sqlite-shm ]; do
		echo -e "\nThis profile is used. Close your browser or email program and try again.\n"
		read -p "Press any key to continue."
	done
}
```

на венде при запуске prefsCleaner.sh у меня аварийное завершение, поэтому не удалю.

но все равно спасибо

**Comment by dimqua** [comment]
> Он там всегда будет, это неотъемлемо. А для проклятой венды программа wget не подтянется

Так, если уж на то пошло, то и никакого шелла в винде тоже нет (разве что WSL есть, но только в десятке), поэтому, кмк, это не самая большая проблема. Вообще в винде тоже есть curl, но это алиас для `Invoke-WebRequest` и он не все ключи понимает (например, `-s`), но вот это работает:
>curl  "ссылкаНаЧтоЛибо" -o "ПутьСохранения"

Для `perfsCleaner.sh`, если это единственная проблема, можно использовать этот костыль:
```
if [ "$(uname)" = "Linux" ]; then
    ...
elif [ "$(expr substr $(uname) 1 5)" = "MINGW" ]; then
   ...
fi
```

**Comment by dimqua** [comment]
Кстати, `perfsCleaner.sh` у меня на винде отрабатывает, во всяком случае, проверка на наличие `webappsstore.sqlite-shm`.

**Comment by bogachenko** [comment]
@dimqua 

> Так, если уж на то пошло, то и никакого шелла в винде тоже нет (разве что WSL есть)

я например не использую WSL, у меня от васянского скрипта, это который удаляет хуйню от майкосфт отвалился магазин (не проблема, ибо годного там ничего нет). И поэтому я даже его при желании не смогу установить, поэтому я использую VM.

> Кстати, `perfsCleaner.sh` у меня на винде отрабатывает, во всяком случае, проверка на наличие `webappsstore.sqlite-shm`. 

это как? поподробней, как так у меня не получается? он делает очищает pref.js ? можешь создать папку поместить туда 2 файла pref.js (написав туда 2-3 настройки) и user.js (настройки с обратным значением) и запустить perfsCleaner.sh.


Я не могу. Меня просто выбрасывает.

**Comment by dimqua** [comment]
Похоже, что обе ошибки из-за того, что в скрипте шебанг `#!/bin/sh`, а не `#!/bin/bash`, я по привычке запускал так:
> bash perfsCleaner.sh

Поэтому не столкнулся с этим.

**Comment by bogachenko** [comment]
@dimqua совневаюсь, что это вообще когданибудь заработает...

изменил на `#!/bin/bash`
теперь ошибка вот такая вот
![default](https://user-images.githubusercontent.com/8535285/52511911-27240080-2bfa-11e9-9463-72bf72d48e8a.png)

**Comment by dimqua** [comment]
А если так `bash.exe .\prefsCleaner.sh` или так `.\bash.exe .\prefsCleaner.sh`?

**Comment by bogachenko** [comment]
не. ничего не поменялось. да ладно забей. путь будут 2 файла
